image: git.geomar.de:11411/wind-products/windeval_docker:v1.1.0
before_script:
  - source activate windeval

pytest_and_coverage:
  stage: test
  script:
    - pip install .
    - pytest

lint:
  stage: test
  allow_failure: false
  script:
    - flake8 src/ --max-line-length=88
    - black --check src/

pages:
  stage: deploy
  script:
    - apt-get update && apt-get install make
    - pip install sphinx recommonmark sphinx_rtd_theme sphinx-autodoc-typehints
    - cd docs/
    - make clean
    - make html
    - cd ..
    - mv doc/_build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
